title: Przemek's homepage
tagline: lost in time
description: > 
   My humble home in the great space of the Internet... a bit about my projects,
   as well as the projects, books, movies that I like and recommend. 
   
baseurl: "/testblog" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
paginate: 10
paginate_path: "/testblog/page:num"

simple_search: http://google.com/search
markdown: kramdown
kramdown:
  extensions:
    - autolink
    - footnotes
    - smart
timezone:    Europe/Stockholm

github_username:  przemekr
author :
  name : 'Przemyslaw Rzepecki'
  email : przemekr@sdfeu.org
  github_username : przemekr
  linkedin_username: przemekr
  bitbucket_username: przemekr
